server:
  port: 8090

spring:
  application:
    name: msvc-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_manage_system
    username: root
    password: 1513
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: sql
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
