eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # El gateway va a estar activo y va redireccionar los
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**  # Eliminar espacio extra
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**  # Eliminar espacio extra